db.courses.insert({courseId : "BM101", instructorId : "2020csb1117@iitrpr.ac.in", advisorId : "advisor@gmail.cpm"})
db.courses.insert({courseId : "CS302", instructorId : "2020csb1117@iitrpr.ac.in", advisorId : "advisor@gmail.com"})
db.courses.insert({courseId : "HS104", instructorId : "2020csb1117@iitrpr.ac.in", advisorId : "advisor@gmail.cpm"})
db.courses.insert({courseId : "CS301", instructorId : "2020csb1117@iitrpr.ac.in", advisorId : "advisor@gmail.com"})
db.courses.insert({courseId : "CP301", instructorId : "2020csb1117@iitrpr.ac.in", advisorId : "advisor@gmail.cpm"})
db.courses.insert({courseId : "CN111", instructorId : "2020csb1117@iitrpr.ac.in", advisorId : "advisor@gmail.com"})